name: Tests

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
    pull_request:
      branches:
        - main
        - develop

jobs:
  build:
    runs-on: ubuntu-latest
    startegy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: action/checkout@v2k
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - run: npm ci
      - run: npm test
